sonar.projectKey=Alex21221006_Proyecto_Calidad_Agente
sonar.organization=alex21221006
sonar.projectName=Proyecto_Calidad_Agente
sonar.projectVersion=1.0

sonar.sources=api
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
